dbt_config:
  api_token: "dbtu_eSYPMSIP9HgMU6DfDOs2kz-grNCJvDgIw0VB_ZZFn2bpxbd2ng"
  account_id: "70471823461483"
  job_id: "70471823472253"
  skip_dbt: false
email_config:
  sender_email: "ateeqh.rehman@dynpro.com"
  password: "Habeeb@123"
  recipient_email: "sharwari.shinde@dynpro.com,devender.dagar@dynpro.com"
  subject: "DBT Cloud Job Status: [JOB_NAME] - [ENVIRONMENT]"
  message: "This is a status update for your DBT Cloud job.\n\nJob Name: [JOB_NAME]\nEnvironment: [ENVIRONMENT]\n\nThis notification is sent by Dagster."
  smtp_server: "smtp.office365.com"
  smtp_port: 587
